extends "res://scripts/interactable.gd"


func on_interact() -> void:
	open_text("Bouteille", """Cette bouteille contient une note illisible. 

B.... .u e. v....... .. mal...
...s c... .. ..ff... ... .... .....t.. .. c.....
....... .. d... ê...
.... .tt...... .. .... ... ... t.ône .. ..ss.. .. ..î..
... ... ......ll. .. ... ê... vil...
.. b.tin ....r..... ....p....
...s ..... .. ch.... . ... p....

.""")
